In [1]:
import numpy as np

In [2]:
list1=[1,2,3,4]

In [4]:
arr=np.array(list1)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4]


In [7]:
nested_list=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((3,3),np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [16]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [17]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [18]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.linspace(0,100,11,dtype=np.int8)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int8)

In [20]:
np.eye(4) #for creating identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(2)

array([0.0389386 , 0.34368372])

In [22]:
np.random.rand(5,5) #used for creating wieghts in deep learning

array([[0.70590481, 0.27734883, 0.83064508, 0.71926756, 0.00947096],
       [0.38099988, 0.14983983, 0.74260369, 0.23956835, 0.15146879],
       [0.86657976, 0.16607255, 0.41994405, 0.29927285, 0.02377519],
       [0.88428597, 0.79995127, 0.34602958, 0.05113865, 0.46014309],
       [0.4710492 , 0.41809601, 0.30132388, 0.49120771, 0.59704342]])

In [23]:
np.random.randn(5,5)

array([[ 0.73581641,  1.33843719,  0.17483952, -0.46139697, -0.59069656],
       [-0.33198481,  1.43461217,  0.20104128,  0.01852402, -0.79327699],
       [ 0.34716933, -0.00511051, -0.11992064,  1.51343443,  3.00938441],
       [ 0.24919247, -0.03432396, -0.65939182, -0.16342635,  2.05272886],
       [-0.91789476,  0.08270314,  1.05559596, -0.22446028,  0.1966331 ]])

In [24]:
np.random.randint(1,100)

61

In [25]:
np.random.randint(1,100,4)

array([ 6, 26, 73, 63])

In [26]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(5,5) #can be reshaped only to the product of all the shapes being the total number of values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [32]:
ranarr

array([45, 19,  1, 49, 11, 27,  6,  0, 21,  9])

In [34]:
ranarr.max()

49

In [35]:
ranarr.argmax()

3

In [36]:
ranarr.min()

0

In [37]:
ranarr.argmin()

7

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr1 = arr.reshape(5,5)

In [40]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr1.transpose()

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [43]:
arr1.dtype

dtype('int32')

In [45]:
np.multiply(arr,arr1)

ValueError: operands could not be broadcast together with shapes (25,) (5,5) 

In [46]:
arr_example = np.arange(0,11)

In [47]:
arr_example

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr_example[8]

8

In [49]:
arr_example[0:5]

array([0, 1, 2, 3, 4])

In [50]:
[x:x+1 for x in arr_example]

SyntaxError: invalid syntax (<ipython-input-50-4eb3c2c8e97a>, line 1)

In [51]:
arr_example[8]=100

In [52]:
arr_example[8]

100

In [53]:
arr_example[0:5]=100

In [54]:
arr_example

array([100, 100, 100, 100, 100,   5,   6,   7, 100,   9,  10])

In [55]:
slice_of_arr=arr[0:6] #this will not create a new memory for slice_of_arr, instead slice_of_arr is just pointing to part of arr

In [56]:
slice_of_arr[:]=99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
slice_of_arr1=arr[0:6].copy()

In [62]:
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

In [63]:
slice_of_arr1[:]=1

In [64]:
slice_of_arr1

array([1, 1, 1, 1, 1, 1])

In [65]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
arr_2d=np.array([[5,10,15],[20,25,30],[30,35,40]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [68]:
arr_2d[1]

array([20, 25, 30])

In [69]:
arr_2d[1][1]

25

In [70]:
arr_2d[1,1]

25

In [71]:
arr_2d[:2,:1]

array([[ 5],
       [20]])

In [72]:
arr_2d[1:,1:]

array([[25, 30],
       [35, 40]])

In [73]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [35, 40]])

In [75]:
arr3=np.arange(1,11)

In [77]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr3>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
bool_arr3=arr3>4

In [80]:
bool_arr3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [81]:
arr3[bool_arr3]

array([ 5,  6,  7,  8,  9, 10])

In [82]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [83]:
arr1

array([[99, 99, 99, 99, 99],
       [99,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [84]:
bool_arr1=arr1<16

In [85]:
bool_arr1

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [86]:
arr1[bool_arr1]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [87]:
arr5=np.arange(0,10)

In [88]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr5*arr5

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [90]:
arr5+arr5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
arr5/arr5

C:\Users\manoj\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [92]:
1/arr5

C:\Users\manoj\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [93]:
np.sqrt(arr5)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [94]:
np.exp(arr5)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [95]:
np.sin(arr5)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [96]:
np.log(arr5)

C:\Users\manoj\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [97]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 35, 40]])

In [98]:
arr_2d.flatten()

array([ 5, 10, 15, 20, 25, 30, 30, 35, 40])