In [1]:
import numpy as np
x = [3,4]
np.linalg.norm(x) # 5.0

5.0

In [2]:
import numpy as np
# Compute the direction of a vector x.
def direction(x):
 return x/np.linalg.norm(x) 

In [3]:
u = np.array([3,4])
w = direction(u)
print(w) # [0.6 , 0.8]

[0.6 0.8]


In [4]:
u_1 = np.array([3,4])
u_2 = np.array([30,40])
print(direction(u_1)) # [0.6 , 0.8]
print(direction(u_2)) # [0.6 , 0.8]

[0.6 0.8]
[0.6 0.8]


In [5]:
np.linalg.norm(np.array([0.6, 0.8])) # 1.0

1.0

In [6]:
u_2 = np.array([35,45])
print(direction(u_2))

[0.61394061 0.78935222]


In [7]:
np.linalg.norm(np.array(direction(u_2))) # 1.0

1.0

In [8]:
import math
import numpy as np
def geometric_dot_product(x,y, theta):
    x_norm = np.linalg.norm(x)
    y_norm = np.linalg.norm(y)
    return x_norm * y_norm * math.cos(math.radians(theta))


In [9]:
theta = 45
x = [3,5]
y = [8,2]
print(geometric_dot_product(x,y,theta)) # 34.0

34.00000000000001


In [10]:
def dot_product(x,y):
    result = 0
    for i in range(len(x)):
        result = result + x[i]*y[i]
    return result

In [11]:
x = [3,5]
y = [8,2]
print(dot_product(x,y)) # 34

34


In [1]:
import numpy as np
x = np.array([3,5])
y = np.array([8,2])
print(np.dot(x,y)) # 34

34


In [5]:
np.random.random_sample(4)

array([0.59977768, 0.07320739, 0.12131469, 0.79631603])

In [6]:
np.random.random(4)

array([0.49018896, 0.30692974, 0.33801282, 0.5736141 ])

In [8]:
np.random.randint(-5,5,4)

array([-2, -2, -3,  0])

In [9]:
np.random.randrange(1)

AttributeError: module 'numpy.random' has no attribute 'randrange'

In [10]:
import random

In [12]:
random.randrange(-5,5,1)

2